insert into menuentity values (1,'월요일','조식','현미밥','삶은 계란', '시금치 나물', '오이 무침', '미역국', 1, 1);
insert into menuentity values (2,'월요일','중식','현미밥','구운 닭가슴살', '브로콜리 찜', '당근 볶음', '두부국', 1, 1 );
insert into menuentity values (3,'월요일','석식','퀴노아','연어 구이', '채소 볶음', '김치', '렌틸콩 수프', 1, 1);
insert into menuentity values (4,'화요일','조식','현미밥','아보카도 슬라이스', '파프리카 볶음', '무생채', '콩나물국', 1, 1);
insert into menuentity values (5,'화요일','중식','흑미밥','구운 두부', '가지 구이', '미역 무침', '시금치국', 1, 1);
insert into menuentity values (6,'화요일','석식','현미밥','구운 닭가슴살', '쌈채소', '당근채', '된장국', 1, 1);
insert into menuentity values (7,'수요일','조식','현미밥','스크램블 에그', '브로콜리 찜', '오이 무침', '북어국', 1, 1);
insert into menuentity values (8,'수요일','중식','퀴노아','생선구이', '시금치 나물', '채소 샐러드', '미소국', 1, 1);
insert into menuentity values (9,'수요일','석식','현미밥','병아리콩 샐러드', '볶은 애호박', '김치', '두부국', 1, 1);
insert into menuentity values (10,'목요일','조식','현미밥','삶은 계란', '시금치 무침', '방울토마토', '애호박국', 1, 1);
insert into menuentity values (11,'목요일','중식','흑미밥','구운 연어', '브로콜리 볶음', '무생채', '두부 국', 1, 1);
insert into menuentity values (12,'목요일','석식','퀴노아','구운 닭가슴살', '채소 볶음', '김치', '렌틸콩 스프', 1, 1);
insert into menuentity values (13,'금요일','조식','현미밥','아몬드', '파프리카 볶음', '오이 무침', '시금치국', 1, 1);
insert into menuentity values (14,'금요일','중식','현미밥','구운 두부', '가지 무침', '쌈채소', '미역국', 1, 1);
insert into menuentity values (15,'금요일','석식','퀴노아','구운 고등어', '브로콜리 찜', '김치', '채소 스프', 1, 1);
insert into menuentity values (16,'토요일','조식','통곡물 토스트','아보카도', '삶은 계란', '방울토마토', '견과류 믹스', 1, 1);
insert into menuentity values (17,'토요일','중식','현미밥','닭가슴살 샐러드', '쌈채소', '오이 스틱', '두부국', 1, 1);
insert into menuentity values (18,'토요일','석식','퀴노아','구운 연어', '채소 볶음', '김치', '렌틸콩 수프', 1, 1);
insert into menuentity values (19,'일요일','조식','현미밥','삶은 계란', '시금치 나물', '미역 무침', '콩나물국', 1, 1);
insert into menuentity values (20,'일요일','중식','흑미밥','구운 닭가슴살', '브로콜리 볶음', '당근채', '미소국', 1, 1);
insert into menuentity values (21,'일요일','석식','퀴노아','두부 스테이크', '아스파라거스 볶음', '김치', '채소 스프', 1, 1);
-- 2. 혈당 70mg/dl 이하, 콜레스테롤 200-239 사이
insert into menuentity values (22,'월요일','조식','현미밥','삶은 계란', '시금치 나물', '김치', '미역국', 1, 2);
insert into menuentity values (23,'월요일','중식','현미밥','두부 스테이크', '브로콜리 볶음', '무생채', '북어국' , 1, 2);
insert into menuentity values (24,'월요일','석식','퀴노아','구운 고등어', '쌈채소', '', '렌틸콩 수프', 1, 2);
insert into menuentity values (25,'화요일','조식','귀리죽','아보카도 슬라이스', '파프리카 볶음', '오이 무침', '콩나물국', 1, 2);
insert into menuentity values (26,'화요일','중식','흑미밥','구운 닭가슴살', '가지 구이', '양배추 샐러드', '시금치국', 1, 2);
insert into menuentity values (27,'화요일','석식','현미밥','연어 스테이크', '쌈채소', '볶은 양배추', '된장국', 1, 2);
insert into menuentity values (28,'수요일','조식','통곡물 토스트','스크램블 에그', '방울토마토', '아몬드', '', 1, 2);
insert into menuentity values (29,'수요일','중식','현미밥','구운 두부', '시금치 나물', '당근 볶음', '미소국', 1, 2);
insert into menuentity values (30,'수요일','석식','퀴노아','닭가슴살 구이', '브로콜리 찜', '', '채소 스프', 1, 2);
insert into menuentity values (31,'목요일','조식','현미밥','삶은 계란', '무생채', '채소 샐러드', '애호박국', 1, 2);
insert into menuentity values (32,'목요일','중식','흑미밥','생선구이 (고등어)', '볶은 아스파라거스', '콩나물 무침', '시금치국', 1, 2);
insert into menuentity values (33,'목요일','석식','퀴노아','구운 두부', '쌈채소', '', '렌틸콩 스프', 1, 2);
insert into menuentity values (34,'금요일','조식','오트밀','아몬드', '사과 슬라이스', '', '콩나물국', 1, 2);
insert into menuentity values (35,'금요일','중식','현미밥','닭가슴살 샐러드', '볶은 채소 (브로콜리, 당근)', '', '미역국', 1, 2);
insert into menuentity values (36,'금요일','석식','퀴노아','구운 연어', '시금치 나물', '', '채소 스프', 1, 2);
insert into menuentity values (37,'토요일','조식','귀리죽','삶은 계란', '아보카도', '', '시금치국', 1, 2);
insert into menuentity values (38,'토요일','중식','현미밥','구운 고등어', '미역 무침', '채소 샐러드', '두부국', 1, 2);
insert into menuentity values (39,'토요일','석식','퀴노아','구운 닭가슴살', '브로콜리 볶음', '', '렌틸콩 수프', 1, 2);
insert into menuentity values (40,'일요일','조식','현미밥','삶은 계란', '파프리카 볶음', '', '북어국', 1, 2);
insert into menuentity values (41,'일요일','중식','흑미밥','구운 두부', '쌈채소', '당근채', '미소국', 1, 2);
insert into menuentity values (42,'일요일','석식','퀴노아','연어 구이', '아스파라거스 볶음', '', '채소 스프', 1, 2);
-- 3. 혈당 70mg/dl 이하, 콜레스테롤 240이상
insert into menuentity values (43,'월요일','조식','귀리밥','삶은 계란', '시금치 나물', '오이 무침', '미역국', 1, 3);
insert into menuentity values (44,'월요일','중식','현미밥','구운 닭가슴살', '브로콜리 볶음', '당근 볶음', '북어국', 1, 3);
insert into menuentity values (45,'월요일','석식','퀴노아','연어 구이', '채소 볶음', '', '렌틸콩 수프', 1, 3);
insert into menuentity values (46,'화요일','조식','통곡물 토스트','아보카도', '방울토마토', '아몬드', '', 1, 3);
insert into menuentity values (47,'화요일','중식','흑미밥','구운 두부', '가지 구이', '미역 무침', '시금치국', 1, 3);
insert into menuentity values (48,'화요일','석식','현미밥','구운 연어', '쌈채소', '볶은 양배추', '된장국', 1, 3);
insert into menuentity values (49,'수요일','조식','현미밥','스크램블 에그', '브로콜리 찜', '오이 무침', '콩나물국', 1, 3);
insert into menuentity values (50,'수요일','중식','퀴노아','생선구이 (고등어)', '시금치 나물', '채소 샐러드', '미소국', 1, 3);
insert into menuentity values (51,'수요일','석식','현미밥','병아리콩 샐러드', '볶은 애호박', '', '두부국', 1, 3);
insert into menuentity values (52,'목요일','조식','현미밥','삶은 계란', '무생채', '채소 샐러드', '애호박국', 1, 3);
insert into menuentity values (53,'목요일','중식','흑미밥','구운 닭가슴살', '브로콜리 볶음', '쌈채소', '두부 국', 1, 3);
insert into menuentity values (54,'목요일','석식','퀴노아','구운 연어', '볶은 시금치', '', '렌틸콩 스프', 1, 3);
insert into menuentity values (55,'금요일','조식','오트밀','아몬드', '바나나 슬라이스', '', '콩나물국', 1, 3);
insert into menuentity values (56,'금요일','중식','현미밥','닭가슴살 샐러드', '볶은 채소 (브로콜리, 당근)', '', '미역국', 1, 3);
insert into menuentity values (57,'금요일','석식','퀴노아','구운 두부', '쌈채소', '', '채소 스프', 1, 3);
insert into menuentity values (58,'토요일','조식','귀리죽','삶은 계란', '아보카도 슬라이스', '', '시금치국', 1, 3);
insert into menuentity values (59,'토요일','중식','현미밥','구운 고등어', '미역 무침', '채소 샐러드', '두부국', 1, 3);
insert into menuentity values (60,'토요일','석식','퀴노아','구운 닭가슴살', '볶은 아스파라거스', '', '렌틸콩 수프', 1, 3);
insert into menuentity values (61,'일요일','조식','현미밥','삶은 계란', '파프리카 볶음', '', '북어국', 1, 3);
insert into menuentity values (62,'일요일','중식','흑미밥','구운 두부', '쌈채소', '당근채', '미소국', 1, 3);
insert into menuentity values (63,'일요일','석식','퀴노아','연어 구이', '볶은 양배추', '', '채소 스프', 1, 3);
-- 4. 혈당 70-100mg/dl, 콜레스테롤 200미만
insert into menuentity values (64,'월요일','조식','현미밥','삶은 계란', '시금치 나물', '오이 무침', '미역국', 2, 1);
insert into menuentity values (65,'월요일','중식','현미밥','구운 닭가슴살', '브로콜리 찜', '당근 볶음', '두부국', 2, 1);
insert into menuentity values (66,'월요일','석식','퀴노아','연어 구이', '채소 볶음', '', '렌틸콩 수프', 2, 1);
insert into menuentity values (67,'화요일','조식','귀리죽','아보카도 슬라이스', '파프리카 볶음', '무생채', '콩나물국', 2, 1);
insert into menuentity values (68,'화요일','중식','흑미밥','구운 두부', '가지 구이', '양배추 샐러드', '시금치국', 2, 1);
insert into menuentity values (69,'화요일','석식','현미밥','구운 연어', '쌈채소', '볶은 양배추', '된장국', 2, 1);
insert into menuentity values (70,'수요일','조식','통곡물 토스트','스크램블 에그', '방울토마토', '아몬드', '', 2, 1);
insert into menuentity values (71,'수요일','중식','현미밥','생선구이 (고등어)', '시금치 나물', '채소 샐러드', '미소국', 2, 1);
insert into menuentity values (72,'수요일','석식','퀴노아','병아리콩 샐러드', '볶은 애호박', '', '두부국', 2, 1);
insert into menuentity values (73,'목요일','조식','현미밥','삶은 계란', '무생채', '채소 샐러드', '애호박국', 2, 1);
insert into menuentity values (74,'목요일','중식','흑미밥','구운 닭가슴살', '브로콜리 볶음', '쌈채소', '두부국', 2, 1);
insert into menuentity values (75,'목요일','석식','퀴노아','구운 연어', '볶은 시금치', '', '렌틸콩 수프', 2, 1);
insert into menuentity values (76,'금요일','조식','오트밀','아몬드', '바나나 슬라이스', '', '콩나물국', 2, 1);
insert into menuentity values (77,'금요일','중식','현미밥','닭가슴살 샐러드', '볶은 채소 (브로콜리, 당근)', '', '미역국', 2, 1);
insert into menuentity values (78,'금요일','석식','퀴노아','구운 두부', '쌈채소', '', '채소 스프', 2, 1);
insert into menuentity values (79,'토요일','조식','귀리죽','삶은 계란', '아보카도 슬라이스', '', '시금치국', 2, 1);
insert into menuentity values (80,'토요일','중식','현미밥','구운 고등어', '미역 무침', '채소 샐러드', '두부국', 2, 1);
insert into menuentity values (81,'토요일','석식','퀴노아','구운 닭가슴살', '볶은 아스파라거스', '', '렌틸콩 수프', 2, 1);
insert into menuentity values (82,'일요일','조식','현미밥','삶은 계란', '파프리카 볶음', '', '북어국', 2, 1);
insert into menuentity values (83,'일요일','중식','흑미밥','구운 두부', '쌈채소', '당근채', '미소국', 2, 1);
insert into menuentity values (84,'일요일','석식','퀴노아','연어 구이', '볶은 양배추', '', '채소 스프', 2, 1);
-- 5. 혈당 70-100mg/dl, 콜레스테롤 200-239 사이
insert into menuentity values (85,'월요일','조식','현미밥','스크램블 에그', '시금치 무침', '방울토마토', '미역국', 2, 2);
insert into menuentity values (86,'월요일','중식','현미밥','닭가슴살 구이', '브로콜리 볶음', '무생채', '북어국', 2, 2);
insert into menuentity values (87,'월요일','석식','퀴노아','구운 연어', '아스파라거스 볶음', '', '채소 스프', 2, 2);
insert into menuentity values (88,'화요일','조식','귀리죽','삶은 계란', '아보카도 슬라이스', '오이 무침', '콩나물국', 2, 2);
insert into menuentity values (89,'화요일','중식','흑미밥','고등어 구이', '시금치 나물', '당근 볶음', '두부국', 2, 2);
insert into menuentity values (90,'화요일','석식','현미밥','구운 두부', '볶은 브로콜리', '쌈채소', '된장국', 2, 2);
insert into menuentity values (91,'수요일','조식','통곡물 토스트','아몬드', '사과 슬라이스', '', '애호박국', 2, 2);
insert into menuentity values (92,'수요일','중식','현미밥','닭가슴살 샐러드', '가지 구이', '양배추 샐러드', '미소국', 2, 2);
insert into menuentity values (93,'수요일','석식','퀴노아','생선구이 (고등어)', '볶은 양배추', '', '렌틸콩 수프', 2, 2);
insert into menuentity values (94,'목요일','조식','현미밥','두부 스테이크', '파프리카 볶음', '김치', '시금치국', 2, 2);
insert into menuentity values (95,'목요일','중식','흑미밥','연어 스테이크', '브로콜리 찜', '무생채', '콩나물국', 2, 2);
insert into menuentity values (96,'목요일','석식','퀴노아','닭가슴살 구이', '볶은 애호박', '', '채소 스프', 2, 2);
insert into menuentity values (97,'금요일','조식','오트밀','아몬드', '바나나', '', '미역국', 2, 2);
insert into menuentity values (98,'금요일','중식','현미밥','구운 두부', '볶은 채소 (당근, 브로콜리)', '', '시금치국', 2, 2);
insert into menuentity values (99,'금요일','석식','퀴노아','구운 연어', '쌈채소', '', '렌틸콩 수프', 2, 2);
insert into menuentity values (100,'토요일','조식','귀리죽','삶은 계란', '파프리카 볶음', '', '북어국', 2, 2);
insert into menuentity values (101,'토요일','중식','현미밥','구운 닭가슴살', '미역 무침', '채소 샐러드', '두부국', 2, 2);
insert into menuentity values (102,'토요일','석식','퀴노아','생선구이', '볶은 아스파라거스', '', '채소 스프', 2, 2);
insert into menuentity values (103,'일요일','조식','현미밥','스크램블 에그', '오이 무침', '', '콩나물국', 2, 2);
insert into menuentity values (104,'일요일','중식','흑미밥','구운 두부', '브로콜리 볶음', '당근채', '미소국', 2, 2);
insert into menuentity values (105,'일요일','석식','퀴노아','구운 고등어', '볶은 시금치', '', '렌틸콩 수프', 2, 2);
-- 6. 혈당 70-100mg/dl, 콜레스테롤 240이상
insert into menuentity values (106,'월요일','조식','현미밥','계란찜', '시금치 나물', '방울토마토', '미역국', 2, 3);
insert into menuentity values (107,'월요일','중식','흑미밥','구운 닭가슴살', '브로콜리 볶음', '무생채', '북어국', 2, 3);
insert into menuentity values (108,'월요일','석식','퀴노아','연어 스테이크', '볶은 아스파라거스', '', '렌틸콩 스프', 2, 3);
insert into menuentity values (109,'화요일','조식','귀리죽','아보카도 슬라이스', '파프리카 볶음', '오이 무침', '콩나물국', 2, 3);
insert into menuentity values (110,'화요일','중식','현미밥','고등어 구이', '시금치 나물', '당근 볶음', '두부국', 2, 3);
insert into menuentity values (111,'화요일','석식','현미밥','구운 두부', '볶은 양배추', '김치', '된장국', 2, 3);
insert into menuentity values (112,'수요일','조식','통곡물 토스트','삶은 계란', '아몬드', '사과 슬라이스', '애호박국', 2, 3);
insert into menuentity values (113,'수요일','중식','현미밥','닭가슴살 샐러드', '가지 구이', '양배추 샐러드', '미소국', 2, 3);
insert into menuentity values (114,'수요일','석식','퀴노아','생선구이 (고등어)', '볶은 브로콜리', '', '채소 스프', 2, 3);
insert into menuentity values (115,'목요일','조식','현미밥','두부 스테이크', '파프리카 볶음', '김치', '시금치국', 2, 3);
insert into menuentity values (116,'목요일','중식','흑미밥','연어 구이', '브로콜리 찜', '무생채', '콩나물국', 2, 3);
insert into menuentity values (117,'목요일','석식','퀴노아','구운 닭가슴살', '볶은 애호박', '', '렌틸콩 수프', 2, 3);
insert into menuentity values (118,'금요일','조식','오트밀','아몬드', '바나나', '', '미역국', 2, 3);
insert into menuentity values (119,'금요일','중식','현미밥','구운 두부', '볶은 채소 (당근, 브로콜리)', '', '시금치국', 2, 3);
insert into menuentity values (120,'금요일','석식','퀴노아','구운 연어', '쌈채소', '', '채소 스프', 2, 3);
insert into menuentity values (121,'토요일','조식','귀리죽','삶은 계란', '파프리카 볶음', '', '북어국', 2, 3);
insert into menuentity values (122,'토요일','중식','현미밥','구운 닭가슴살', '미역 무침', '채소 샐러드', '두부국', 2, 3);
insert into menuentity values (123,'토요일','석식','퀴노아','생선구이', '볶은 아스파라거스', '', '채소 스프', 2, 3);
insert into menuentity values (124,'일요일','조식','현미밥','스크램블 에그', '오이 무침', '', '콩나물국', 2, 3);
insert into menuentity values (125,'일요일','중식','흑미밥','구운 두부', '브로콜리 볶음', '당근채', '미소국', 2, 3);
insert into menuentity values (126,'일요일','석식','퀴노아','구운 고등어', '볶은 시금치', '', '렌틸콩 수프', 2, 3);
-- 7. 혈당 100 이상, 콜레스테롤 200미만
insert into menuentity values (127,'월요일','조식','현미밥','삶은 계란', '시금치 나물', '오이 무침', '미역국', 3, 1);
insert into menuentity values (128,'월요일','중식','현미밥','구운 닭가슴살', '브로콜리 찜', '당근 볶음', '두부국', 3, 1);
insert into menuentity values (129,'월요일','석식','퀴노아','연어 구이', '볶은 아스파라거스', '', '렌틸콩 스프', 3, 1);
insert into menuentity values (130,'화요일','조식','귀리죽','아보카도 슬라이스', '파프리카 볶음', '무생채', '콩나물국', 3, 1);
insert into menuentity values (131,'화요일','중식','흑미밥','구운 두부', '가지 구이', '양배추 샐러드', '시금치국', 3, 1);
insert into menuentity values (132,'화요일','석식','현미밥','구운 연어', '쌈채소', '볶은 양배추', '된장국', 3, 1);
insert into menuentity values (133,'수요일','조식','통곡물 토스트','스크램블 에그', '방울토마토', '', '애호박국', 3, 1);
insert into menuentity values (134,'수요일','중식','현미밥','닭가슴살 샐러드', '가지 구이', '시금치 나물', '미소국', 3, 1);
insert into menuentity values (135,'수요일','석식','퀴노아','생선구이 (고등어)', '볶은 브로콜리', '', '채소 스프', 3, 1);
insert into menuentity values (136,'목요일','조식','현미밥','두부 스테이크', '파프리카 볶음', '김치', '시금치국', 3, 1);
insert into menuentity values (137,'목요일','중식','흑미밥','연어 구이', '브로콜리 찜', '무생채', '콩나물국', 3, 1);
insert into menuentity values (138,'목요일','석식','퀴노아','구운 닭가슴살', '볶은 애호박', '', '렌틸콩 수프', 3, 1);
insert into menuentity values (139,'금요일','조식','오트밀','아몬드', '바나나 슬라이스', '', '미역국', 3, 1);
insert into menuentity values (140,'금요일','중식','현미밥','구운 두부', '볶은 채소 (당근, 브로콜리)', '', '시금치국', 3, 1);
insert into menuentity values (141,'금요일','석식','퀴노아','구운 연어', '쌈채소', '', '채소 스프', 3, 1);
insert into menuentity values (142,'토요일','조식','귀리죽','삶은 계란', '파프리카 볶음', '', '북어국', 3, 1);
insert into menuentity values (143,'토요일','중식','현미밥','구운 닭가슴살', '미역 무침', '채소 샐러드', '두부국', 3, 1);
insert into menuentity values (144,'토요일','석식','퀴노아','생선구이', '볶은 아스파라거스', '', '채소 스프', 3, 1);
insert into menuentity values (145,'일요일','조식','현미밥','스크램블 에그', '오이 무침', '', '콩나물국', 3, 1);
insert into menuentity values (146,'일요일','중식','흑미밥','구운 두부', '브로콜리 볶음', '당근채', '미소국', 3, 1);
insert into menuentity values (147,'일요일','석식','퀴노아','구운 고등어', '볶은 시금치', '', '렌틸콩 수프', 3, 1);
-- 8. 혈당 100 이상, 콜레스테롤 200-239 사이
insert into menuentity values (148,'월요일','조식','현미밥','삶은 계란', '시금치 나물', '오이 무침', '미역국', 3, 2);
insert into menuentity values (149,'월요일','중식','흑미밥','구운 닭가슴살', '브로콜리 볶음', '당근 볶음', '두부국', 3, 2);
insert into menuentity values (150,'월요일','석식','퀴노아','연어 구이', '볶은 아스파라거스', '', '렌틸콩 스프', 3, 2);
insert into menuentity values (151,'화요일','조식','귀리죽','아보카도 슬라이스', '파프리카 볶음', '무생채', '콩나물국', 3, 2);
insert into menuentity values (152,'화요일','중식','현미밥','구운 두부', '가지 구이', '양배추 샐러드', '시금치국', 3, 2);
insert into menuentity values (153,'화요일','석식','현미밥','구운 연어', '쌈채소', '볶은 양배추', '된장국', 3, 2);
insert into menuentity values (154,'수요일','조식','통곡물 토스트','스크램블 에그', '방울토마토', '', '애호박국', 3, 2);
insert into menuentity values (155,'수요일','중식','현미밥','닭가슴살 샐러드', '가지 구이', '시금치 나물', '미소국', 3, 2);
insert into menuentity values (156,'수요일','석식','퀴노아','생선구이 (고등어)', '볶은 브로콜리', '', '채소 스프', 3, 2);
insert into menuentity values (157,'목요일','조식','현미밥','두부 스테이크', '파프리카 볶음', '김치', '시금치국', 3, 2);
insert into menuentity values (158,'목요일','중식','흑미밥','연어 구이', '브로콜리 찜', '무생채', '콩나물국', 3, 2);
insert into menuentity values (159,'목요일','석식','퀴노아','구운 닭가슴살', '볶은 애호박', '', '렌틸콩 수프', 3, 2);
insert into menuentity values (160,'금요일','조식','오트밀','아몬드', '바나나 슬라이스', '', '미역국', 3, 2);
insert into menuentity values (161,'금요일','중식','현미밥','구운 두부', '볶은 채소 (당근, 브로콜리)', '', '시금치국', 3, 2);
insert into menuentity values (162,'금요일','석식','퀴노아','구운 연어', '쌈채소', '', '채소 스프', 3, 2);
insert into menuentity values (163,'토요일','조식','귀리죽','삶은 계란', '파프리카 볶음', '', '북어국', 3, 2);
insert into menuentity values (164,'토요일','중식','현미밥','구운 닭가슴살', '미역 무침', '채소 샐러드', '두부국', 3, 2);
insert into menuentity values (165,'토요일','석식','퀴노아','생선구이', '볶은 아스파라거스', '', '채소 스프', 3, 2);
insert into menuentity values (166,'일요일','조식','현미밥','콩나물국', '오이 무침', '', '콩나물국', 3, 2);
insert into menuentity values (167,'일요일','중식','흑미밥','구운 두부', '브로콜리 볶음', '당근채', '미소국', 3, 2);
insert into menuentity values (168,'일요일','석식','퀴노아','구운 고등어', '볶은 시금치', '', '렌틸콩 수프', 3, 2);
-- 9. 혈당 100 이상, 콜레스테롤 400이상
insert into menuentity values (169,'월요일','조식','현미밥','삶은 계란', '시금치 나물', '오이 무침', '미역국', 3, 3);
insert into menuentity values (170,'월요일','중식','현미밥','구운 닭가슴살', '브로콜리 볶음', '당근 볶음', '두부국', 3, 3);
insert into menuentity values (171,'월요일','석식','퀴노아','연어 구이', '볶은 아스파라거스', '', '렌틸콩 수프', 3, 3);
insert into menuentity values (172,'화요일','조식','귀리죽','아보카도 슬라이스', '파프리카 볶음', '무생채', '콩나물국', 3, 3);
insert into menuentity values (173,'화요일','중식','흑미밥','구운 두부', '가지 구이', '양배추 샐러드', '시금치국', 3, 3);
insert into menuentity values (174,'화요일','석식','현미밥','구운 연어', '쌈채소', '볶은 양배추', '된장국', 3, 3);
insert into menuentity values (175,'수요일','조식','통곡물 토스트','스크램블 에그', '방울토마토', '', '애호박국', 3, 3);
insert into menuentity values (176,'수요일','중식','현미밥','닭가슴살 샐러드', '가지 구이', '시금치 나물', '미소국', 3, 3);
insert into menuentity values (177,'수요일','석식','퀴노아','생선구이 (고등어)', '볶은 브로콜리', '', '채소 스프', 3, 3);
insert into menuentity values (178,'목요일','조식','현미밥','두부 스테이크', '파프리카 볶음', '김치', '시금치국', 3, 3);
insert into menuentity values (179,'목요일','중식','흑미밥','연어 구이', '브로콜리 찜', '무생채', '콩나물국', 3, 3);
insert into menuentity values (180,'목요일','석식','퀴노아','구운 닭가슴살', '볶은 애호박', '', '렌틸콩 수프', 3, 3);
insert into menuentity values (181,'금요일','조식','오트밀','아몬드', '바나나 슬라이스', '', '미역국', 3, 3);
insert into menuentity values (182,'금요일','중식','현미밥','구운 두부', '볶은 채소 (당근, 브로콜리)', '', '시금치국', 3, 3);
insert into menuentity values (183,'금요일','석식','퀴노아','구운 연어', '쌈채소', '', '채소 스프', 3, 3);
insert into menuentity values (184,'토요일','조식','귀리죽','삶은 계란', '파프리카 볶음', '', '북어국', 3, 3);
insert into menuentity values (185,'토요일','중식','현미밥','구운 닭가슴살', '미역 무침', '채소 샐러드', '두부국', 3, 3);
insert into menuentity values (186,'토요일','석식','퀴노아','생선구이', '볶은 아스파라거스', '', '채소 스프', 3, 3);
insert into menuentity values (187,'일요일','조식','현미밥','스크램블 에그', '오이 무침', '', '콩나물국', 3, 3);
insert into menuentity values (188,'일요일','중식','흑미밥','구운 두부', '브로콜리 볶음', '당근채', '미소국', 3, 3);
insert into menuentity values (189,'일요일','석식','퀴노아','구운 고등어', '볶은 시금치', '', '렌틸콩 수프', 3, 3);
commit;
